import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { Suspense } from "react";
import MoveToTop from "./components/MoveToTop";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "GitHub Users",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <MoveToTop />
        <Suspense fallback={<div>Loading....</div>}>
          {children}
        </Suspense>
      </body>
    </html>
  );
}
